import Head from "next/head";
// import Image from "next/image";
// import { Inter } from "@next/font/google";
import next from "next";
import styles from "@/styles/Home.module.css";

export default function Home() {
  console.log(styles);
  return (
    <>
      kdrai
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>hello there</h1>
      </div>
    </>
  );
}
